plugins:
  - jekyll-remote-theme
remote_theme: "mmistakes/so-simple-theme"
title: Linusable's GitHub homepage
description: Public personnal webpages for some professionnal, associative and private projects.
timezone: Europe/Brussels
logo: "/images/DVillers-UMONS-2012-square.jpg"
